kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: slave-odo
  Name: node-app-slave
  Url:
  - Name: node-app-slave
    Port: 8080
